// Generated by sdk/tools/generate.py; safe native connection records.
use serde::{Serialize, Deserialize};
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct IdentityObservation {
    pub schema: String,
    pub device_identity: String,
    pub display_name: String,
    pub protocol: String,
    pub pairing_available: bool,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HostCandidate {
    pub endpoint: String,
    pub identity: IdentityObservation,
    pub certificate_sha256: String,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum PairingPosture {Pending,Approved,Revoked,Expired,Refused}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PairingObservation {
    pub schema: String,
    pub request_id: String,
    pub posture: PairingPosture,
    pub scope: String,
    pub expires_at_unix_ms: u64,
    pub reason: Option<String>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum ConnectionTransport {Https,Local}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum ConnectionPosture {Unpaired,Pending,Approved,Revoked,Expired,Refused}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ConnectionProfile {
    pub profile_ref: String,
    pub transport: ConnectionTransport,
    pub endpoint: String,
    pub device_identity: String,
    pub peer_identity: String,
    pub display_name: String,
    pub client_name: String,
    pub pairing_posture: ConnectionPosture,
    pub expires_at_unix_ms: Option<u64>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DiscoveredHost {
    pub service_name: String,
    pub endpoint: String,
    pub display_name: String,
    pub advertised_device_identity: Option<String>,
    pub trusted: bool,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum OwnerPosture {Approved,Revoked}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum OwnerProfilePosture {Prepared,Claiming,Approved,Revoked}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum OwnerActionKind {PairingOpen,PairingApprove,PairingRevoke,OwnerRevoke,ServiceControlGrant,ServiceControlRevoke}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all="snake_case")]
pub enum OwnerActionPosture {Applied,Refused}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerInvitationPreview {
    pub endpoint: String,
    pub device_identity: String,
    pub invitation_id: String,
    pub expires_at_unix_ms: u64,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerProfile {
    pub profile_ref: String,
    pub endpoint: String,
    pub device_identity: String,
    pub peer_identity: String,
    pub client_name: String,
    pub posture: OwnerProfilePosture,
    pub pending_requests: Vec<String>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerObservation {
    pub schema: String,
    pub scope: String,
    pub owner_ref: String,
    pub client_name: String,
    pub posture: OwnerPosture,
    pub revision: u64,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerPeer {
    pub request_id: String,
    pub client_name: String,
    pub posture: PairingPosture,
    pub scope: String,
    pub expires_at_unix_ms: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_control_granted: Option<bool>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerAdministrationObservation {
    pub schema: String,
    pub scope: String,
    pub owner_ref: String,
    pub revision: u64,
    pub open_until_unix_ms: u64,
    pub peers: Vec<OwnerPeer>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub available_actions: Option<Vec<OwnerActionKind>>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerActionRequest {
    pub schema: String,
    pub request_id: String,
    pub expected_revision: u64,
    pub action: OwnerActionKind,
    pub target_ref: Option<String>,
}
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct OwnerActionReceipt {
    pub schema: String,
    pub scope: String,
    pub owner_ref: String,
    pub request_id: String,
    pub action: OwnerActionKind,
    pub target_ref: Option<String>,
    pub revision: u64,
    pub posture: OwnerActionPosture,
    pub reason: Option<String>,
}
