// Generated by sdk/tools/generate.py; edit contract/management.json.
use serde::{Deserialize, Serialize};
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OperationKind {
    Read,
    Job,
    Control,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum JobState {
    Accepted,
    Running,
    Succeeded,
    Failed,
    Cancelled,
    Indeterminate,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum DispatchState {
    NotDispatched,
    OutcomeUnavailable,
    Completed,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResponseStatus {
    Ok,
    Refused,
    Unavailable,
    Unsupported,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HostState {
    Running,
    Stopped,
    Unavailable,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Reasoning {
    Disabled,
    Enabled,
    Low,
    Maximum,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EmptyInput {
}
#[derive(Clone, Serialize, Deserialize)]
pub struct OperationCapability {
    pub operation: String,
    pub kind: OperationKind,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Capabilities {
    pub protocol: String,
    pub producer_version: String,
    pub local_protocol: u64,
    pub operations: Vec<OperationCapability>,
    pub limits: std::collections::BTreeMap<String, u64>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Job {
    pub job_id: String,
    pub operation: String,
    pub state: JobState,
    pub submitted_at_unix_ms: u64,
    pub updated_at_unix_ms: u64,
    pub input: serde_json::Value,
    #[serde(default)]
    pub result: Option<serde_json::Value>,
    #[serde(default)]
    pub reason: Option<String>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct JobInput {
    pub job_id: String,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct JobList {
    pub jobs: Vec<JobSummary>,
    pub retention_limit: u64,
    pub truncated: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ListInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelInput {
    pub model: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EngineLoadInput {
    pub profile: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context_capacity: Option<u64>,
    pub host_instance: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EngineInput {
    pub model: String,
    pub generation: u64,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionInput {
    pub model: String,
    pub generation: u64,
    pub name: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionForkInput {
    pub model: String,
    pub generation: u64,
    pub name: String,
    pub fork_name: String,
    pub maximum_prefix_bytes: u64,
    pub host_instance: String,
    pub session_identity: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationInput {
    pub model: String,
    pub generation: u64,
    pub name: String,
    pub prompt: String,
    pub maximum_new_tokens: u64,
    pub reasoning: Reasoning,
    pub host_instance: String,
    pub session_identity: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GenerationCancelInput {
    pub model: String,
    pub generation: u64,
    pub name: String,
    pub host_instance: String,
    pub session_identity: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EventsInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub after_sequence: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Source {
    pub provider: String,
    pub repository: String,
    pub revision: String,
    pub origin_uri: String,
    pub storage: String,
    pub path: String,
    pub format: String,
    pub precision: String,
    pub verification: String,
    pub state: String,
    pub digest: String,
    pub size_bytes: u64,
    pub size_known: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Publication {
    pub provider: String,
    pub repository: String,
    pub revision: String,
    pub filename: String,
    pub sha256: String,
    pub manifest_filename: String,
    pub manifest_sha256: String,
    pub size_bytes: u64,
    pub state: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Artifact {
    pub identity: String,
    pub path: String,
    pub format: String,
    pub quant_precision: String,
    pub size_bytes: u64,
    pub tensor_count: u64,
    pub local_available: bool,
    pub remote_locations: Vec<Publication>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct EngineCapabilities {
    pub input_mask: u64,
    pub output_mask: u64,
    pub properties: u64,
    pub maximum_input_parts: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inputs: Option<Vec<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub outputs: Option<Vec<String>>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct RuntimeProfile {
    pub identity: String,
    pub artifact_identity: String,
    pub backend: String,
    pub engine_kind: String,
    pub strategy: String,
    pub context: u64,
    pub launchable: bool,
    pub blocker: String,
    pub capabilities: EngineCapabilities,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub readiness: Option<ProfileReadiness>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub compatibility: Option<String>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Model {
    pub selector: String,
    pub identity: String,
    pub name: String,
    pub family: String,
    pub origin: String,
    pub format: String,
    pub quant_precision: String,
    pub state: String,
    pub execution: String,
    pub location: String,
    #[serde(default)]
    pub selected_profile: Option<String>,
    pub representation_count: u64,
    pub sources: Vec<Source>,
    pub representations: Vec<Artifact>,
    pub profiles: Vec<RuntimeProfile>,
    pub loaded_engines: Vec<LoadedModelEngine>,
    pub components: Vec<serde_json::Value>,
    pub working_set: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ModelList {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    pub models: Vec<Model>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub truncated: Option<bool>,
    pub runtime_observation: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ModelDetail {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    pub model: Model,
    pub runtime_observation: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct EngineCapacity {
    pub sessions: u64,
    pub runnable_work: u64,
    pub physical_sequence_width: u64,
    pub cooperative_scheduling: bool,
    pub compatible_operation_batching: bool,
    pub continuous_batching: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ResourceObservation {
    pub schema_version: u64,
    pub available: u64,
    pub placement: String,
    pub physical_residency_known: bool,
    pub unified_memory: bool,
    pub components: u64,
    pub model_artifact_bytes: u64,
    pub model_mapped_bytes: u64,
    pub model_prepared_bytes: u64,
    pub model_explicit_host_bytes: u64,
    pub model_explicit_device_bytes: u64,
    pub model_device_addressable_bytes: u64,
    pub session_attention_allocated_bytes: u64,
    pub session_attention_resident_bytes: u64,
    pub session_attention_virtual_bytes: u64,
    pub session_attention_page_table_bytes: u64,
    pub session_recurrent_state_bytes: u64,
    pub session_convolution_state_bytes: u64,
    pub session_candidate_state_bytes: u64,
    pub session_physical_state_bytes: u64,
    pub activation_arena_current_bytes: u64,
    pub activation_arena_peak_bytes: u64,
    pub workspace_current_bytes: u64,
    pub workspace_peak_bytes: u64,
    pub transient_current_bytes: u64,
    pub transient_peak_bytes: u64,
    pub process_rss_current_bytes: u64,
    pub process_rss_peak_bytes: u64,
    pub logical_upload_bytes: u64,
    pub logical_download_bytes: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Engine {
    pub alias: String,
    pub generation: u64,
    pub state: String,
    pub backend: u64,
    pub engine_kind: String,
    pub execution_strategy: String,
    pub execution_ready: bool,
    pub continuous_batching: bool,
    pub context_capacity: u64,
    pub prefill_chunk_tokens: u64,
    pub maximum_new_tokens: u64,
    pub maximum_sessions: u64,
    pub configured_physical_sequence_width: u64,
    pub active_work: u64,
    pub sessions: u64,
    pub attached_clients: u64,
    pub model_leases: u64,
    pub activity: String,
    pub mapped_package_bytes: u64,
    pub resident_host_bytes: u64,
    pub resident_device_bytes: u64,
    pub prepared_bytes: u64,
    pub capacity: EngineCapacity,
    pub resources: ResourceObservation,
    pub capabilities: EngineCapabilities,
    pub target: String,
    pub model_identity: String,
    pub specialization_identity: String,
    pub runtime_binding_identity: String,
    pub artifact_identity: String,
    pub capacity_plan_identity: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct EngineList {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    pub engines: Vec<Engine>,
    #[serde(default)]
    pub host_instance: Option<String>,
    pub truncated: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Session {
    pub name: String,
    pub identity: String,
    pub state: String,
    pub position: u64,
    pub turns: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub generation: Option<u64>,
    #[serde(default)]
    pub context_used: Option<u64>,
    #[serde(default)]
    pub kv_used_bytes: Option<u64>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct SessionList {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    pub sessions: Vec<Session>,
    #[serde(default)]
    pub host_instance: Option<String>,
    pub truncated: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct SessionDetail {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<String>,
    #[serde(default)]
    pub session: Option<Session>,
    pub host_instance: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct HostSnapshot {
    pub schema: String,
    pub protocol: u64,
    pub status: i64,
    pub host_ready: bool,
    pub engine_count: u64,
    pub loaded_engine_count: u64,
    pub draining_engine_count: u64,
    pub maximum_engines: u64,
    pub workers: u64,
    pub session_count: u64,
    pub requests: u64,
    pub uptime_ns: u64,
    pub active_sessions: u64,
    pub total_sessions: u64,
    pub queue_depth: u64,
    pub queue_capacity: u64,
    pub active_requests: u64,
    pub completed_requests: u64,
    pub failed_requests: u64,
    pub cancelled_requests: u64,
    pub openai_enabled: bool,
    pub openai_ready: bool,
    pub openai_port: u64,
    pub rss_bytes: u64,
    pub peak_rss_bytes: u64,
    pub mapped_artifact_bytes: u64,
    pub resident_host_bytes: u64,
    pub resident_device_bytes: u64,
    pub resources: ResourceObservation,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct HostObservation {
    pub state: HostState,
    #[serde(default)]
    pub status: Option<HostSnapshot>,
    #[serde(default)]
    pub host_instance: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_known: Option<Option<LastKnownHost>>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Event {
    pub sequence: u64,
    pub process: u64,
    pub wall_time_ns: u64,
    pub monotonic_time_ns: u64,
    pub kind: String,
    pub severity: u64,
    pub session: String,
    pub request: String,
    pub turn: String,
    pub phase: String,
    pub identity: String,
    pub measurement_available: u64,
    pub measurement_completed: u64,
    pub measurement_total: u64,
    pub measurement_duration_ns: u64,
    pub seconds: f64,
    pub rate: f64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Events {
    pub events: Vec<Event>,
    pub next_sequence: u64,
    pub truncated: bool,
    pub host_instance: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EngineMutationInput {
    pub model: String,
    pub generation: u64,
    pub host_instance: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionMutationInput {
    pub model: String,
    pub generation: u64,
    pub name: String,
    pub host_instance: String,
    pub session_identity: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SessionCreateInput {
    pub model: String,
    pub generation: u64,
    pub name: String,
    pub host_instance: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ModelListInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SearchInput {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub filter: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub page: Option<u32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<u32>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct InspectInput {
    pub repository: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PackageInput {
    pub model: String,
    pub package: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceInput {
    pub source: String,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AcquisitionInput {
    pub repository: String,
    pub revision: String,
    pub representation: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authentication: Option<RegistryAuthentication>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credential_ref: Option<String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RegistryAuthentication {
    Anonymous,
    Configured,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AcquisitionCancelInput {
    pub source: String,
    pub expected_operation_id: String,
    pub expected_generation: u64,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BuildInput {
    pub model: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quant: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub expected_plan: Option<String>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StorageInput {
    pub model: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub include_caches: Option<bool>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct RemoteRepresentation {
    pub identity: String,
    pub format: String,
    pub precision: String,
    pub precision_evidence: String,
    pub file_pattern: String,
    pub compatibility: String,
    pub file_count: u64,
    pub size_bytes: u64,
    pub size_known: bool,
    pub provisional: bool,
    pub local: serde_json::Value,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct RemoteFile {
    pub path: String,
    pub kind: String,
    pub representation: String,
    pub size_bytes: u64,
    pub size_known: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct RemoteModel {
    pub provider: String,
    pub repository: String,
    pub requested_revision: String,
    pub resolved_revision: String,
    pub kind: String,
    pub kind_evidence: String,
    pub model_identity: String,
    pub family_affinity: String,
    pub family_evidence: String,
    pub architecture: String,
    pub base_model: String,
    pub support_stage: String,
    pub product_status: String,
    pub engine_state: String,
    pub local_source_revision: bool,
    pub local_package_revision: bool,
    pub local_source: bool,
    pub local_package: bool,
    pub local_related_revision: bool,
    pub kind_provisional: bool,
    pub canonical: bool,
    pub ranking_score: f64,
    pub provider_rank: u64,
    pub gated_known: bool,
    pub gated: bool,
    pub parameter_count_known: bool,
    pub parameter_count: u64,
    pub representations: Vec<RemoteRepresentation>,
    pub files: Vec<RemoteFile>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct SearchResult {
    pub schema: String,
    pub authorities: Vec<String>,
    pub query: String,
    pub provider_result_count: u64,
    pub models: Vec<RemoteModel>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct PackageDetail {
    pub model: String,
    pub package: Artifact,
    pub profiles: Vec<RuntimeProfile>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Acquisition {
    pub schema: String,
    pub operation_id: String,
    pub generation: u64,
    pub provider: String,
    pub repository: String,
    pub target_id: String,
    pub family: String,
    pub revision: String,
    pub selection_identity: String,
    pub lifecycle: String,
    pub health: String,
    #[serde(default)]
    pub current_object: Option<String>,
    pub active: bool,
    pub stop_available: bool,
    pub resume_available: bool,
    pub reason: String,
    #[serde(default)]
    pub result: Option<String>,
    #[serde(default)]
    pub expected_bytes: Option<u64>,
    #[serde(default)]
    pub committed_bytes: Option<u64>,
    #[serde(default)]
    pub selected_files: Option<u64>,
    #[serde(default)]
    pub completed_files: Option<u64>,
    #[serde(default)]
    pub current_rate_bytes_per_second: Option<u64>,
    #[serde(default)]
    pub rolling_rate_bytes_per_second: Option<u64>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct AcquisitionObservation {
    pub acquisition: Acquisition,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct RegistryAccounts {
    pub providers: Vec<RegistryAccount>,
    pub credential_configuration: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct StorageObservation {
    pub schema: String,
    pub rows: Vec<serde_json::Value>,
    pub logical_bytes: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct RegistryAccount {
    pub provider: String,
    pub auth_state: String,
    pub account: String,
    pub credential_source: String,
    pub cli_present: bool,
    pub status: String,
    pub blocker: String,
    #[serde(default)]
    pub credential_ref: Option<String>,
    pub credential_provisioning: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct LoadedModelEngine {
    pub profile_identity: String,
    pub variant: String,
    pub generation: u64,
    pub sessions: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct AcquisitionResumeInput {
    pub source: String,
    pub expected_operation_id: String,
    pub expected_generation: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authentication: Option<RegistryAuthentication>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub credential_ref: Option<String>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OutputChannel {
    FinalText,
    PublicReasoning,
    ToolCall,
    ToolResult,
    Control,
    Error,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct GenerationChannel {
    pub channel: OutputChannel,
    pub text: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bytes: Option<Vec<u32>>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct GenerationMetrics {
    pub prompt_tokens: u64,
    pub generated_tokens: u64,
    pub reasoning_tokens: u64,
    pub final_tokens: u64,
    pub stop_reason: u64,
    pub total_completion_seconds: f64,
    pub final_position: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct GenerationResult {
    pub host_instance: String,
    pub model: String,
    pub generation: u64,
    pub session: String,
    pub channels: Vec<GenerationChannel>,
    #[serde(default)]
    pub turn_identity: Option<String>,
    pub complete: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<Event>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics: Option<GenerationMetrics>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Acknowledgement {
    pub host_instance: String,
    pub acknowledged: bool,
    pub reason: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct EngineResult {
    pub host_instance: String,
    pub engine: Engine,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct SessionResult {
    pub host_instance: String,
    pub session: Session,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct BuildResult {
    pub schema: String,
    pub model: String,
    pub state: String,
    pub changed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quant: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub profile: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub action: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub creation_reproducible: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub runtime_binding: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub binding_published: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub planning: Option<BuildPlanning>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct JobSummary {
    pub job_id: String,
    pub operation: String,
    pub state: JobState,
    pub submitted_at_unix_ms: u64,
    pub updated_at_unix_ms: u64,
    #[serde(default)]
    pub reason: Option<String>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RepresentationKind {
    Source,
    Package,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EvictInput {
    pub model: String,
    pub representation: String,
    pub kind: RepresentationKind,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm: Option<bool>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct SourceVerification {
    pub source: String,
    pub revision: String,
    pub payload_identity: String,
    pub payload_trust: String,
    pub shards: u64,
    pub tensors: u64,
    pub logical_tensor_bytes: u64,
    pub physical_bytes_read: u64,
    pub published_identity_reused: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct PackageVerification {
    pub model: String,
    pub package: String,
    pub checked: bool,
    pub passed: bool,
    pub native_status: i64,
    pub sha256: String,
    pub digest_status: String,
    pub format: String,
    pub tensor_count: u64,
    pub file_size: u64,
    pub error_count: u64,
    pub warning_count: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct Eviction {
    pub schema: String,
    pub changed: bool,
    pub local: bool,
    pub logical_bytes: u64,
    pub allocated_bytes: u64,
    pub path: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ProfileScan {
    pub candidates: Vec<ProfileCandidate>,
    pub truncated: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ProfileCandidate {
    pub alias: String,
    pub family: String,
    pub model: String,
    pub scope: String,
    pub artifact_class: String,
    pub qprofile: String,
    pub calibration: String,
    pub path: String,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileInput {
    pub profile: String,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ProfileVerification {
    pub profile: String,
    pub passed: bool,
    pub identity_status: String,
    pub metadata_status: String,
    pub readiness_status: String,
    pub status: String,
    pub reason: String,
    pub registered_sha256: String,
    pub current_sha256: String,
    pub registered_size: u64,
    pub current_size: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileCreateInput {
    pub model: String,
    pub package: String,
    pub alias: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub base_profile: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub context: Option<u64>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ProfileCreated {
    pub profile: String,
    pub package: String,
    pub file_size: u64,
    pub created: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProfileRemoveInput {
    pub profile: String,
    pub expected_package: String,
    pub confirm: bool,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct ProfileRemoved {
    pub profile: String,
    pub removed: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SourceCleanupInput {
    pub source: String,
    pub expected_operation_id: String,
    pub expected_generation: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stale_locks: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub failed_partials: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub receipts: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub logs: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provider_cache: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirm: Option<bool>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct SourceCleanup {
    pub schema: String,
    pub target: String,
    pub status: String,
    pub dry_run: bool,
    pub yes: bool,
    pub delete_candidates: Vec<String>,
    pub deleted_paths: u64,
    pub missing: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ProfileReadiness {
    Ready,
    Blocked,
    Incompatible,
    Unavailable,
    Unknown,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct LastKnownHost {
    pub host_instance: String,
    pub status: HostSnapshot,
    pub observed_at_unix_ms: u64,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct BuildPlanning {
    pub schema: String,
    pub readiness: ProfileReadiness,
    pub basis: BuildPlanningBasis,
    #[serde(default)]
    pub reason: Option<String>,
    #[serde(default)]
    pub native_status: Option<i64>,
    #[serde(default)]
    pub owner: Option<String>,
    #[serde(default)]
    pub execution_strategy: Option<String>,
    pub runtime_admission: BuildEvidencePosture,
    pub quality_evidence: BuildEvidencePosture,
    pub performance_evidence: BuildEvidencePosture,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuildPlanningBasis {
    AdmittedRecipe,
    VerifiedProfile,
    NotAdmitted,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuildEvidencePosture {
    NotEvaluated,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HostOwnership {
    Managed,
    External,
    Unconfigured,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct HostControl {
    pub schema: String,
    pub ownership: HostOwnership,
    pub revision: u64,
    pub state: HostState,
    #[serde(default)]
    pub host_instance: Option<String>,
    pub configured: bool,
    pub service_control_granted: bool,
    pub can_start: bool,
    pub can_stop: bool,
    pub can_restart: bool,
    #[serde(default)]
    pub reason: Option<String>,
    #[serde(default)]
    pub inference_port: Option<u64>,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HostStartInput {
    pub expected_revision: u64,
}
#[derive(Clone, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct HostStopInput {
    pub expected_revision: u64,
    pub host_instance: String,
    pub acknowledge_disruption: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum HostControlPhase {
    Stopping,
    Stopped,
    Starting,
    Running,
}
#[derive(Clone, Serialize, Deserialize)]
pub struct HostControlResult {
    pub schema: String,
    pub phase: HostControlPhase,
    pub revision: u64,
    #[serde(default)]
    pub previous_host_instance: Option<String>,
    #[serde(default)]
    pub host_instance: Option<String>,
    pub models_restored: bool,
    #[serde(flatten)]
    pub additional: std::collections::BTreeMap<String, serde_json::Value>,
}
pub mod operations {
    use super::*;
    use crate::management::Operation;
    pub struct ManagementCapabilities;
    impl Operation for ManagementCapabilities {
        type Input = super::EmptyInput;
        type Output = super::Capabilities;
        const ID: &'static str = "management.capabilities";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct ModelList;
    impl Operation for ModelList {
        type Input = super::ModelListInput;
        type Output = super::ModelList;
        const ID: &'static str = "model.list";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct ModelGet;
    impl Operation for ModelGet {
        type Input = super::ModelInput;
        type Output = super::ModelDetail;
        const ID: &'static str = "model.get";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct EngineList;
    impl Operation for EngineList {
        type Input = super::EmptyInput;
        type Output = super::EngineList;
        const ID: &'static str = "engine.list";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct EngineLoad;
    impl Operation for EngineLoad {
        type Input = super::EngineLoadInput;
        type Output = super::Job;
        const ID: &'static str = "engine.load";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct EngineUnload;
    impl Operation for EngineUnload {
        type Input = super::EngineMutationInput;
        type Output = super::Job;
        const ID: &'static str = "engine.unload";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct HostGet;
    impl Operation for HostGet {
        type Input = super::EmptyInput;
        type Output = super::HostObservation;
        const ID: &'static str = "host.get";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct SessionList;
    impl Operation for SessionList {
        type Input = super::EngineInput;
        type Output = super::SessionList;
        const ID: &'static str = "session.list";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct SessionGet;
    impl Operation for SessionGet {
        type Input = super::SessionInput;
        type Output = super::SessionDetail;
        const ID: &'static str = "session.get";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct SessionCreate;
    impl Operation for SessionCreate {
        type Input = super::SessionCreateInput;
        type Output = super::Job;
        const ID: &'static str = "session.create";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct SessionFork;
    impl Operation for SessionFork {
        type Input = super::SessionForkInput;
        type Output = super::Job;
        const ID: &'static str = "session.fork";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct SessionClose;
    impl Operation for SessionClose {
        type Input = super::SessionMutationInput;
        type Output = super::Job;
        const ID: &'static str = "session.close";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct GenerationStart;
    impl Operation for GenerationStart {
        type Input = super::GenerationInput;
        type Output = super::Job;
        const ID: &'static str = "generation.start";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct GenerationCancel;
    impl Operation for GenerationCancel {
        type Input = super::GenerationCancelInput;
        type Output = super::Job;
        const ID: &'static str = "generation.cancel";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct JobList;
    impl Operation for JobList {
        type Input = super::ListInput;
        type Output = super::JobList;
        const ID: &'static str = "job.list";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct JobGet;
    impl Operation for JobGet {
        type Input = super::JobInput;
        type Output = super::Job;
        const ID: &'static str = "job.get";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct ObserveEvents;
    impl Operation for ObserveEvents {
        type Input = super::EventsInput;
        type Output = super::Events;
        const ID: &'static str = "observe.events";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct ModelSearch;
    impl Operation for ModelSearch {
        type Input = super::SearchInput;
        type Output = super::SearchResult;
        const ID: &'static str = "model.search";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct ModelInspect;
    impl Operation for ModelInspect {
        type Input = super::InspectInput;
        type Output = super::SearchResult;
        const ID: &'static str = "model.inspect";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct ModelStorage;
    impl Operation for ModelStorage {
        type Input = super::StorageInput;
        type Output = super::StorageObservation;
        const ID: &'static str = "model.storage";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct RegistryAccounts;
    impl Operation for RegistryAccounts {
        type Input = super::EmptyInput;
        type Output = super::RegistryAccounts;
        const ID: &'static str = "registry.accounts";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct PackageGet;
    impl Operation for PackageGet {
        type Input = super::PackageInput;
        type Output = super::PackageDetail;
        const ID: &'static str = "package.get";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct AcquisitionGet;
    impl Operation for AcquisitionGet {
        type Input = super::SourceInput;
        type Output = super::AcquisitionObservation;
        const ID: &'static str = "acquisition.get";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct AcquisitionStart;
    impl Operation for AcquisitionStart {
        type Input = super::AcquisitionInput;
        type Output = super::Job;
        const ID: &'static str = "acquisition.start";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct AcquisitionResume;
    impl Operation for AcquisitionResume {
        type Input = super::AcquisitionResumeInput;
        type Output = super::Job;
        const ID: &'static str = "acquisition.resume";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct AcquisitionCancel;
    impl Operation for AcquisitionCancel {
        type Input = super::AcquisitionCancelInput;
        type Output = super::Job;
        const ID: &'static str = "acquisition.cancel";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct BuildStart;
    impl Operation for BuildStart {
        type Input = super::BuildInput;
        type Output = super::Job;
        const ID: &'static str = "build.start";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct SessionReset;
    impl Operation for SessionReset {
        type Input = super::SessionMutationInput;
        type Output = super::Job;
        const ID: &'static str = "session.reset";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct SourceVerify;
    impl Operation for SourceVerify {
        type Input = super::SourceInput;
        type Output = super::Job;
        const ID: &'static str = "source.verify";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct PackageVerify;
    impl Operation for PackageVerify {
        type Input = super::PackageInput;
        type Output = super::Job;
        const ID: &'static str = "package.verify";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct ModelEvict;
    impl Operation for ModelEvict {
        type Input = super::EvictInput;
        type Output = super::Job;
        const ID: &'static str = "model.evict";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct ProfileScan;
    impl Operation for ProfileScan {
        type Input = super::EmptyInput;
        type Output = super::Job;
        const ID: &'static str = "profile.scan";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct ProfileVerify;
    impl Operation for ProfileVerify {
        type Input = super::ProfileInput;
        type Output = super::Job;
        const ID: &'static str = "profile.verify";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct ProfileCreate;
    impl Operation for ProfileCreate {
        type Input = super::ProfileCreateInput;
        type Output = super::Job;
        const ID: &'static str = "profile.create";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct ProfileRemove;
    impl Operation for ProfileRemove {
        type Input = super::ProfileRemoveInput;
        type Output = super::Job;
        const ID: &'static str = "profile.remove";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct SourceCleanup;
    impl Operation for SourceCleanup {
        type Input = super::SourceCleanupInput;
        type Output = super::Job;
        const ID: &'static str = "source.cleanup";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct HostControl;
    impl Operation for HostControl {
        type Input = super::EmptyInput;
        type Output = super::HostControl;
        const ID: &'static str = "host.control";
        const KIND: OperationKind = OperationKind::Read;
    }
    pub struct HostStart;
    impl Operation for HostStart {
        type Input = super::HostStartInput;
        type Output = super::Job;
        const ID: &'static str = "host.start";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct HostStop;
    impl Operation for HostStop {
        type Input = super::HostStopInput;
        type Output = super::Job;
        const ID: &'static str = "host.stop";
        const KIND: OperationKind = OperationKind::Job;
    }
    pub struct HostRestart;
    impl Operation for HostRestart {
        type Input = super::HostStopInput;
        type Output = super::Job;
        const ID: &'static str = "host.restart";
        const KIND: OperationKind = OperationKind::Job;
    }
}
pub(crate) fn validate_input(operation: &str, value: &serde_json::Value) -> Result<(), serde_json::Error> {
    match operation {
        "management.capabilities" => serde_json::from_value::<EmptyInput>(value.clone()).map(|_| ()),
        "model.list" => serde_json::from_value::<ModelListInput>(value.clone()).map(|_| ()),
        "model.get" => serde_json::from_value::<ModelInput>(value.clone()).map(|_| ()),
        "engine.list" => serde_json::from_value::<EmptyInput>(value.clone()).map(|_| ()),
        "engine.load" => serde_json::from_value::<EngineLoadInput>(value.clone()).map(|_| ()),
        "engine.unload" => serde_json::from_value::<EngineMutationInput>(value.clone()).map(|_| ()),
        "host.get" => serde_json::from_value::<EmptyInput>(value.clone()).map(|_| ()),
        "session.list" => serde_json::from_value::<EngineInput>(value.clone()).map(|_| ()),
        "session.get" => serde_json::from_value::<SessionInput>(value.clone()).map(|_| ()),
        "session.create" => serde_json::from_value::<SessionCreateInput>(value.clone()).map(|_| ()),
        "session.fork" => serde_json::from_value::<SessionForkInput>(value.clone()).map(|_| ()),
        "session.close" => serde_json::from_value::<SessionMutationInput>(value.clone()).map(|_| ()),
        "generation.start" => serde_json::from_value::<GenerationInput>(value.clone()).map(|_| ()),
        "generation.cancel" => serde_json::from_value::<GenerationCancelInput>(value.clone()).map(|_| ()),
        "job.list" => serde_json::from_value::<ListInput>(value.clone()).map(|_| ()),
        "job.get" => serde_json::from_value::<JobInput>(value.clone()).map(|_| ()),
        "observe.events" => serde_json::from_value::<EventsInput>(value.clone()).map(|_| ()),
        "model.search" => serde_json::from_value::<SearchInput>(value.clone()).map(|_| ()),
        "model.inspect" => serde_json::from_value::<InspectInput>(value.clone()).map(|_| ()),
        "model.storage" => serde_json::from_value::<StorageInput>(value.clone()).map(|_| ()),
        "registry.accounts" => serde_json::from_value::<EmptyInput>(value.clone()).map(|_| ()),
        "package.get" => serde_json::from_value::<PackageInput>(value.clone()).map(|_| ()),
        "acquisition.get" => serde_json::from_value::<SourceInput>(value.clone()).map(|_| ()),
        "acquisition.start" => serde_json::from_value::<AcquisitionInput>(value.clone()).map(|_| ()),
        "acquisition.resume" => serde_json::from_value::<AcquisitionResumeInput>(value.clone()).map(|_| ()),
        "acquisition.cancel" => serde_json::from_value::<AcquisitionCancelInput>(value.clone()).map(|_| ()),
        "build.start" => serde_json::from_value::<BuildInput>(value.clone()).map(|_| ()),
        "session.reset" => serde_json::from_value::<SessionMutationInput>(value.clone()).map(|_| ()),
        "source.verify" => serde_json::from_value::<SourceInput>(value.clone()).map(|_| ()),
        "package.verify" => serde_json::from_value::<PackageInput>(value.clone()).map(|_| ()),
        "model.evict" => serde_json::from_value::<EvictInput>(value.clone()).map(|_| ()),
        "profile.scan" => serde_json::from_value::<EmptyInput>(value.clone()).map(|_| ()),
        "profile.verify" => serde_json::from_value::<ProfileInput>(value.clone()).map(|_| ()),
        "profile.create" => serde_json::from_value::<ProfileCreateInput>(value.clone()).map(|_| ()),
        "profile.remove" => serde_json::from_value::<ProfileRemoveInput>(value.clone()).map(|_| ()),
        "source.cleanup" => serde_json::from_value::<SourceCleanupInput>(value.clone()).map(|_| ()),
        "host.control" => serde_json::from_value::<EmptyInput>(value.clone()).map(|_| ()),
        "host.start" => serde_json::from_value::<HostStartInput>(value.clone()).map(|_| ()),
        "host.stop" => serde_json::from_value::<HostStopInput>(value.clone()).map(|_| ()),
        "host.restart" => serde_json::from_value::<HostStopInput>(value.clone()).map(|_| ()),
        _ => Err(serde::de::Error::custom("unknown operation")),
    }
}
pub(crate) fn validate_projection(operation: &str, value: &serde_json::Value) -> Result<(), serde_json::Error> {
    match operation {
        "management.capabilities" => serde_json::from_value::<Capabilities>(value.clone()).map(|_| ()),
        "model.list" => serde_json::from_value::<ModelList>(value.clone()).map(|_| ()),
        "model.get" => serde_json::from_value::<ModelDetail>(value.clone()).map(|_| ()),
        "engine.list" => serde_json::from_value::<EngineList>(value.clone()).map(|_| ()),
        "engine.load" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "engine.unload" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "host.get" => serde_json::from_value::<HostObservation>(value.clone()).map(|_| ()),
        "session.list" => serde_json::from_value::<SessionList>(value.clone()).map(|_| ()),
        "session.get" => serde_json::from_value::<SessionDetail>(value.clone()).map(|_| ()),
        "session.create" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "session.fork" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "session.close" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "generation.start" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "generation.cancel" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "job.list" => serde_json::from_value::<JobList>(value.clone()).map(|_| ()),
        "job.get" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "observe.events" => serde_json::from_value::<Events>(value.clone()).map(|_| ()),
        "model.search" => serde_json::from_value::<SearchResult>(value.clone()).map(|_| ()),
        "model.inspect" => serde_json::from_value::<SearchResult>(value.clone()).map(|_| ()),
        "model.storage" => serde_json::from_value::<StorageObservation>(value.clone()).map(|_| ()),
        "registry.accounts" => serde_json::from_value::<RegistryAccounts>(value.clone()).map(|_| ()),
        "package.get" => serde_json::from_value::<PackageDetail>(value.clone()).map(|_| ()),
        "acquisition.get" => serde_json::from_value::<AcquisitionObservation>(value.clone()).map(|_| ()),
        "acquisition.start" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "acquisition.resume" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "acquisition.cancel" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "build.start" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "session.reset" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "source.verify" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "package.verify" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "model.evict" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "profile.scan" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "profile.verify" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "profile.create" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "profile.remove" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "source.cleanup" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "host.control" => serde_json::from_value::<HostControl>(value.clone()).map(|_| ()),
        "host.start" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "host.stop" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        "host.restart" => serde_json::from_value::<Job>(value.clone()).map(|_| ()),
        _ => unreachable!("validated operation"),
    }
}
pub(crate) fn validate_job(job: &Job) -> Result<(), serde_json::Error> {
    match job.operation.as_str() {
        "engine.load" => {
            serde_json::from_value::<EngineLoadInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<EngineResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "engine.unload" => {
            serde_json::from_value::<EngineMutationInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<EngineResult>(result.clone()).map(|_| ()).or_else(|_| serde_json::from_value::<Acknowledgement>(result.clone()).map(|_| ()))?;
            }
            Ok(())
        }
        "session.create" => {
            serde_json::from_value::<SessionCreateInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<SessionResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "session.fork" => {
            serde_json::from_value::<SessionForkInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<SessionResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "session.close" => {
            serde_json::from_value::<SessionMutationInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<Acknowledgement>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "generation.start" => {
            serde_json::from_value::<GenerationInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<GenerationResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "generation.cancel" => {
            serde_json::from_value::<GenerationCancelInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<Acknowledgement>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "acquisition.start" => {
            serde_json::from_value::<AcquisitionInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<AcquisitionObservation>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "acquisition.resume" => {
            serde_json::from_value::<AcquisitionResumeInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<AcquisitionObservation>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "acquisition.cancel" => {
            serde_json::from_value::<AcquisitionCancelInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<AcquisitionObservation>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "build.start" => {
            serde_json::from_value::<BuildInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<BuildResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "session.reset" => {
            serde_json::from_value::<SessionMutationInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<Acknowledgement>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "source.verify" => {
            serde_json::from_value::<SourceInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<SourceVerification>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "package.verify" => {
            serde_json::from_value::<PackageInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<PackageVerification>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "model.evict" => {
            serde_json::from_value::<EvictInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<Eviction>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "profile.scan" => {
            serde_json::from_value::<EmptyInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<ProfileScan>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "profile.verify" => {
            serde_json::from_value::<ProfileInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<ProfileVerification>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "profile.create" => {
            serde_json::from_value::<ProfileCreateInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<ProfileCreated>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "profile.remove" => {
            serde_json::from_value::<ProfileRemoveInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<ProfileRemoved>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "source.cleanup" => {
            serde_json::from_value::<SourceCleanupInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<SourceCleanup>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "host.start" => {
            serde_json::from_value::<HostStartInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<HostControlResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "host.stop" => {
            serde_json::from_value::<HostStopInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<HostControlResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        "host.restart" => {
            serde_json::from_value::<HostStopInput>(job.input.clone())?;
            if let Some(result) = &job.result {
                serde_json::from_value::<HostControlResult>(result.clone()).map(|_| ())?;
            }
            Ok(())
        }
        _ => Err(serde::de::Error::custom("unknown job operation")),
    }
}
pub const OPERATIONS: &[(&str, OperationKind)] = &[
    ("management.capabilities", OperationKind::Read),
    ("model.list", OperationKind::Read),
    ("model.get", OperationKind::Read),
    ("engine.list", OperationKind::Read),
    ("engine.load", OperationKind::Job),
    ("engine.unload", OperationKind::Job),
    ("host.get", OperationKind::Read),
    ("session.list", OperationKind::Read),
    ("session.get", OperationKind::Read),
    ("session.create", OperationKind::Job),
    ("session.fork", OperationKind::Job),
    ("session.close", OperationKind::Job),
    ("generation.start", OperationKind::Job),
    ("generation.cancel", OperationKind::Job),
    ("job.list", OperationKind::Read),
    ("job.get", OperationKind::Read),
    ("observe.events", OperationKind::Read),
    ("model.search", OperationKind::Read),
    ("model.inspect", OperationKind::Read),
    ("model.storage", OperationKind::Read),
    ("registry.accounts", OperationKind::Read),
    ("package.get", OperationKind::Read),
    ("acquisition.get", OperationKind::Read),
    ("acquisition.start", OperationKind::Job),
    ("acquisition.resume", OperationKind::Job),
    ("acquisition.cancel", OperationKind::Job),
    ("build.start", OperationKind::Job),
    ("session.reset", OperationKind::Job),
    ("source.verify", OperationKind::Job),
    ("package.verify", OperationKind::Job),
    ("model.evict", OperationKind::Job),
    ("profile.scan", OperationKind::Job),
    ("profile.verify", OperationKind::Job),
    ("profile.create", OperationKind::Job),
    ("profile.remove", OperationKind::Job),
    ("source.cleanup", OperationKind::Job),
    ("host.control", OperationKind::Read),
    ("host.start", OperationKind::Job),
    ("host.stop", OperationKind::Job),
    ("host.restart", OperationKind::Job),
];
pub struct Models<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn models(&self) -> Models<'_> { Models(self) }
}
impl Models<'_> {
    pub fn list(&self, input: &ModelListInput) -> Result<crate::management::Observation<ModelList>, crate::management::Error> {
        self.0.read::<operations::ModelList>(input)
    }
    pub fn get(&self, input: &ModelInput) -> Result<crate::management::Observation<ModelDetail>, crate::management::Error> {
        self.0.read::<operations::ModelGet>(input)
    }
    pub fn search(&self, input: &SearchInput) -> Result<crate::management::Observation<SearchResult>, crate::management::Error> {
        self.0.read::<operations::ModelSearch>(input)
    }
    pub fn inspect(&self, input: &InspectInput) -> Result<crate::management::Observation<SearchResult>, crate::management::Error> {
        self.0.read::<operations::ModelInspect>(input)
    }
    pub fn storage(&self, input: &StorageInput) -> Result<crate::management::Observation<StorageObservation>, crate::management::Error> {
        self.0.read::<operations::ModelStorage>(input)
    }
    pub fn prepare_evict(&self, input: &EvictInput) -> Result<crate::management::Prepared<operations::ModelEvict>, crate::management::Error> {
        self.0.prepare::<operations::ModelEvict>(input)
    }
}
pub struct Acquisitions<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn acquisitions(&self) -> Acquisitions<'_> { Acquisitions(self) }
}
impl Acquisitions<'_> {
    pub fn get(&self, input: &SourceInput) -> Result<crate::management::Observation<AcquisitionObservation>, crate::management::Error> {
        self.0.read::<operations::AcquisitionGet>(input)
    }
    pub fn prepare_start(&self, input: &AcquisitionInput) -> Result<crate::management::Prepared<operations::AcquisitionStart>, crate::management::Error> {
        self.0.prepare::<operations::AcquisitionStart>(input)
    }
    pub fn prepare_resume(&self, input: &AcquisitionResumeInput) -> Result<crate::management::Prepared<operations::AcquisitionResume>, crate::management::Error> {
        self.0.prepare::<operations::AcquisitionResume>(input)
    }
    pub fn prepare_cancel(&self, input: &AcquisitionCancelInput) -> Result<crate::management::Prepared<operations::AcquisitionCancel>, crate::management::Error> {
        self.0.prepare::<operations::AcquisitionCancel>(input)
    }
}
pub struct Builds<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn builds(&self) -> Builds<'_> { Builds(self) }
}
impl Builds<'_> {
    pub fn prepare_start(&self, input: &BuildInput) -> Result<crate::management::Prepared<operations::BuildStart>, crate::management::Error> {
        self.0.prepare::<operations::BuildStart>(input)
    }
}
pub struct Packages<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn packages(&self) -> Packages<'_> { Packages(self) }
}
impl Packages<'_> {
    pub fn get(&self, input: &PackageInput) -> Result<crate::management::Observation<PackageDetail>, crate::management::Error> {
        self.0.read::<operations::PackageGet>(input)
    }
    pub fn prepare_verify(&self, input: &PackageInput) -> Result<crate::management::Prepared<operations::PackageVerify>, crate::management::Error> {
        self.0.prepare::<operations::PackageVerify>(input)
    }
}
pub struct Hosts<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn hosts(&self) -> Hosts<'_> { Hosts(self) }
}
impl Hosts<'_> {
    pub fn get(&self, input: &EmptyInput) -> Result<crate::management::Observation<HostObservation>, crate::management::Error> {
        self.0.read::<operations::HostGet>(input)
    }
    pub fn control(&self, input: &EmptyInput) -> Result<crate::management::Observation<HostControl>, crate::management::Error> {
        self.0.read::<operations::HostControl>(input)
    }
    pub fn prepare_start(&self, input: &HostStartInput) -> Result<crate::management::Prepared<operations::HostStart>, crate::management::Error> {
        self.0.prepare::<operations::HostStart>(input)
    }
    pub fn prepare_stop(&self, input: &HostStopInput) -> Result<crate::management::Prepared<operations::HostStop>, crate::management::Error> {
        self.0.prepare::<operations::HostStop>(input)
    }
    pub fn prepare_restart(&self, input: &HostStopInput) -> Result<crate::management::Prepared<operations::HostRestart>, crate::management::Error> {
        self.0.prepare::<operations::HostRestart>(input)
    }
}
pub struct Engines<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn engines(&self) -> Engines<'_> { Engines(self) }
}
impl Engines<'_> {
    pub fn list(&self, input: &EmptyInput) -> Result<crate::management::Observation<EngineList>, crate::management::Error> {
        self.0.read::<operations::EngineList>(input)
    }
    pub fn prepare_load(&self, input: &EngineLoadInput) -> Result<crate::management::Prepared<operations::EngineLoad>, crate::management::Error> {
        self.0.prepare::<operations::EngineLoad>(input)
    }
    pub fn prepare_unload(&self, input: &EngineMutationInput) -> Result<crate::management::Prepared<operations::EngineUnload>, crate::management::Error> {
        self.0.prepare::<operations::EngineUnload>(input)
    }
}
pub struct Sessions<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn sessions(&self) -> Sessions<'_> { Sessions(self) }
}
impl Sessions<'_> {
    pub fn list(&self, input: &EngineInput) -> Result<crate::management::Observation<SessionList>, crate::management::Error> {
        self.0.read::<operations::SessionList>(input)
    }
    pub fn get(&self, input: &SessionInput) -> Result<crate::management::Observation<SessionDetail>, crate::management::Error> {
        self.0.read::<operations::SessionGet>(input)
    }
    pub fn prepare_create(&self, input: &SessionCreateInput) -> Result<crate::management::Prepared<operations::SessionCreate>, crate::management::Error> {
        self.0.prepare::<operations::SessionCreate>(input)
    }
    pub fn prepare_fork(&self, input: &SessionForkInput) -> Result<crate::management::Prepared<operations::SessionFork>, crate::management::Error> {
        self.0.prepare::<operations::SessionFork>(input)
    }
    pub fn prepare_close(&self, input: &SessionMutationInput) -> Result<crate::management::Prepared<operations::SessionClose>, crate::management::Error> {
        self.0.prepare::<operations::SessionClose>(input)
    }
    pub fn prepare_reset(&self, input: &SessionMutationInput) -> Result<crate::management::Prepared<operations::SessionReset>, crate::management::Error> {
        self.0.prepare::<operations::SessionReset>(input)
    }
}
pub struct Generations<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn generations(&self) -> Generations<'_> { Generations(self) }
}
impl Generations<'_> {
    pub fn prepare_start(&self, input: &GenerationInput) -> Result<crate::management::Prepared<operations::GenerationStart>, crate::management::Error> {
        self.0.prepare::<operations::GenerationStart>(input)
    }
    pub fn prepare_cancel(&self, input: &GenerationCancelInput) -> Result<crate::management::Prepared<operations::GenerationCancel>, crate::management::Error> {
        self.0.prepare::<operations::GenerationCancel>(input)
    }
}
pub struct Jobs<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn jobs(&self) -> Jobs<'_> { Jobs(self) }
}
impl Jobs<'_> {
    pub fn list(&self, input: &ListInput) -> Result<crate::management::Observation<JobList>, crate::management::Error> {
        self.0.read::<operations::JobList>(input)
    }
    pub fn get(&self, input: &JobInput) -> Result<crate::management::Observation<Job>, crate::management::Error> {
        self.0.read::<operations::JobGet>(input)
    }
}
pub struct Observe<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn observe(&self) -> Observe<'_> { Observe(self) }
}
impl Observe<'_> {
    pub fn events(&self, input: &EventsInput) -> Result<crate::management::Observation<Events>, crate::management::Error> {
        self.0.read::<operations::ObserveEvents>(input)
    }
}
pub struct Sources<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn sources(&self) -> Sources<'_> { Sources(self) }
}
impl Sources<'_> {
    pub fn prepare_verify(&self, input: &SourceInput) -> Result<crate::management::Prepared<operations::SourceVerify>, crate::management::Error> {
        self.0.prepare::<operations::SourceVerify>(input)
    }
    pub fn prepare_cleanup(&self, input: &SourceCleanupInput) -> Result<crate::management::Prepared<operations::SourceCleanup>, crate::management::Error> {
        self.0.prepare::<operations::SourceCleanup>(input)
    }
}
pub struct Profiles<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn profiles(&self) -> Profiles<'_> { Profiles(self) }
}
impl Profiles<'_> {
    pub fn prepare_scan(&self, input: &EmptyInput) -> Result<crate::management::Prepared<operations::ProfileScan>, crate::management::Error> {
        self.0.prepare::<operations::ProfileScan>(input)
    }
    pub fn prepare_verify(&self, input: &ProfileInput) -> Result<crate::management::Prepared<operations::ProfileVerify>, crate::management::Error> {
        self.0.prepare::<operations::ProfileVerify>(input)
    }
    pub fn prepare_create(&self, input: &ProfileCreateInput) -> Result<crate::management::Prepared<operations::ProfileCreate>, crate::management::Error> {
        self.0.prepare::<operations::ProfileCreate>(input)
    }
    pub fn prepare_remove(&self, input: &ProfileRemoveInput) -> Result<crate::management::Prepared<operations::ProfileRemove>, crate::management::Error> {
        self.0.prepare::<operations::ProfileRemove>(input)
    }
}
pub struct Registries<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn registries(&self) -> Registries<'_> { Registries(self) }
}
impl Registries<'_> {
    pub fn accounts(&self, input: &EmptyInput) -> Result<crate::management::Observation<RegistryAccounts>, crate::management::Error> {
        self.0.read::<operations::RegistryAccounts>(input)
    }
}
pub struct Management<'a>(&'a crate::management::Client);
impl crate::management::Client {
    pub fn management(&self) -> Management<'_> { Management(self) }
}
impl Management<'_> {
    pub fn capabilities(&self, input: &EmptyInput) -> Result<crate::management::Observation<Capabilities>, crate::management::Error> {
        self.0.read::<operations::ManagementCapabilities>(input)
    }
}
