// Generated by sdk/tools/generate.py; public YVEX types, no renderer transport.
export type OperationKind = "read" | "job" | "control";
export type JobState = "accepted" | "running" | "succeeded" | "failed" | "cancelled" | "indeterminate";
export type DispatchState = "not_dispatched" | "outcome_unavailable" | "completed";
export type ResponseStatus = "ok" | "refused" | "unavailable" | "unsupported";
export type HostState = "running" | "stopped" | "unavailable";
export type Reasoning = "disabled" | "enabled" | "low" | "maximum";
export interface EmptyInput {
}
export interface OperationCapability {
  operation: string;
  kind: OperationKind;
  [field: string]: unknown;
}
export interface Capabilities {
  protocol: string;
  producer_version: string;
  local_protocol: number;
  operations: Array<OperationCapability>;
  limits: Record<string, number>;
  [field: string]: unknown;
}
export interface JobRecord {
  job_id: string;
  operation: string;
  state: JobState;
  submitted_at_unix_ms: number;
  updated_at_unix_ms: number;
  input: unknown;
  result: unknown | null;
  reason: string | null;
}
export interface JobInput {
  job_id: string;
}
export interface JobList {
  jobs: Array<JobSummary>;
  retention_limit: number;
  truncated: boolean;
  [field: string]: unknown;
}
export interface ListInput {
  limit?: number;
}
export interface ModelInput {
  model: string;
}
export interface EngineLoadInput {
  profile: string;
  context_capacity?: number;
  host_instance: string;
}
export interface EngineInput {
  model: string;
  generation: number;
}
export interface SessionInput {
  model: string;
  generation: number;
  name: string;
}
export interface SessionForkInput {
  model: string;
  generation: number;
  name: string;
  fork_name: string;
  maximum_prefix_bytes: number;
  host_instance: string;
  session_identity: string;
}
export interface GenerationInput {
  model: string;
  generation: number;
  name: string;
  prompt: string;
  maximum_new_tokens: number;
  reasoning: Reasoning;
  host_instance: string;
  session_identity: string;
}
export interface GenerationCancelInput {
  model: string;
  generation: number;
  name: string;
  host_instance: string;
  session_identity: string;
}
export interface EventsInput {
  after_sequence?: number;
  limit?: number;
}
export interface Source {
  provider: string;
  repository: string;
  revision: string;
  origin_uri: string;
  storage: string;
  path: string;
  format: string;
  precision: string;
  verification: string;
  state: string;
  digest: string;
  size_bytes: number;
  size_known: boolean;
  [field: string]: unknown;
}
export interface Publication {
  provider: string;
  repository: string;
  revision: string;
  filename: string;
  sha256: string;
  manifest_filename: string;
  manifest_sha256: string;
  size_bytes: number;
  state: string;
  [field: string]: unknown;
}
export interface Artifact {
  identity: string;
  path: string;
  format: string;
  quant_precision: string;
  size_bytes: number;
  tensor_count: number;
  local_available: boolean;
  remote_locations: Array<Publication>;
  [field: string]: unknown;
}
export interface EngineCapabilities {
  input_mask: number;
  output_mask: number;
  properties: number;
  maximum_input_parts: number;
  inputs?: Array<string>;
  outputs?: Array<string>;
  [field: string]: unknown;
}
export interface RuntimeProfile {
  identity: string;
  artifact_identity: string;
  backend: string;
  engine_kind: string;
  strategy: string;
  context: number;
  launchable: boolean;
  blocker: string;
  capabilities: EngineCapabilities;
  readiness?: ProfileReadiness;
  compatibility?: string;
  [field: string]: unknown;
}
export interface Model {
  selector: string;
  identity: string;
  name: string;
  family: string;
  origin: string;
  format: string;
  quant_precision: string;
  state: string;
  execution: string;
  location: string;
  selected_profile: string | null;
  representation_count: number;
  sources: Array<Source>;
  representations: Array<Artifact>;
  profiles: Array<RuntimeProfile>;
  loaded_engines: Array<LoadedModelEngine>;
  components: Array<unknown>;
  working_set: boolean;
  [field: string]: unknown;
}
export interface ModelList {
  schema?: string;
  models: Array<Model>;
  truncated?: boolean;
  runtime_observation: string;
  [field: string]: unknown;
}
export interface ModelDetail {
  schema?: string;
  model: Model;
  runtime_observation: string;
  [field: string]: unknown;
}
export interface EngineCapacity {
  sessions: number;
  runnable_work: number;
  physical_sequence_width: number;
  cooperative_scheduling: boolean;
  compatible_operation_batching: boolean;
  continuous_batching: boolean;
  [field: string]: unknown;
}
export interface ResourceObservation {
  schema_version: number;
  available: number;
  placement: string;
  physical_residency_known: boolean;
  unified_memory: boolean;
  components: number;
  model_artifact_bytes: number;
  model_mapped_bytes: number;
  model_prepared_bytes: number;
  model_explicit_host_bytes: number;
  model_explicit_device_bytes: number;
  model_device_addressable_bytes: number;
  session_attention_allocated_bytes: number;
  session_attention_resident_bytes: number;
  session_attention_virtual_bytes: number;
  session_attention_page_table_bytes: number;
  session_recurrent_state_bytes: number;
  session_convolution_state_bytes: number;
  session_candidate_state_bytes: number;
  session_physical_state_bytes: number;
  activation_arena_current_bytes: number;
  activation_arena_peak_bytes: number;
  workspace_current_bytes: number;
  workspace_peak_bytes: number;
  transient_current_bytes: number;
  transient_peak_bytes: number;
  process_rss_current_bytes: number;
  process_rss_peak_bytes: number;
  logical_upload_bytes: number;
  logical_download_bytes: number;
  [field: string]: unknown;
}
export interface Engine {
  alias: string;
  generation: number;
  state: string;
  backend: number;
  engine_kind: string;
  execution_strategy: string;
  execution_ready: boolean;
  continuous_batching: boolean;
  context_capacity: number;
  prefill_chunk_tokens: number;
  maximum_new_tokens: number;
  maximum_sessions: number;
  configured_physical_sequence_width: number;
  active_work: number;
  sessions: number;
  attached_clients: number;
  model_leases: number;
  activity: string;
  mapped_package_bytes: number;
  resident_host_bytes: number;
  resident_device_bytes: number;
  prepared_bytes: number;
  capacity: EngineCapacity;
  resources: ResourceObservation;
  capabilities: EngineCapabilities;
  target: string;
  model_identity: string;
  specialization_identity: string;
  runtime_binding_identity: string;
  artifact_identity: string;
  capacity_plan_identity: string;
  [field: string]: unknown;
}
export interface EngineList {
  schema?: string;
  engines: Array<Engine>;
  host_instance: string | null;
  truncated: boolean;
  [field: string]: unknown;
}
export interface Session {
  name: string;
  identity: string;
  state: string;
  position: number;
  turns: number;
  model?: string;
  generation?: number;
  context_used: number | null;
  kv_used_bytes: number | null;
  [field: string]: unknown;
}
export interface SessionList {
  schema?: string;
  sessions: Array<Session>;
  host_instance: string | null;
  truncated: boolean;
  [field: string]: unknown;
}
export interface SessionDetail {
  schema?: string;
  session: Session | null;
  host_instance: string;
  [field: string]: unknown;
}
export interface HostSnapshot {
  schema: string;
  protocol: number;
  status: number;
  host_ready: boolean;
  engine_count: number;
  loaded_engine_count: number;
  draining_engine_count: number;
  maximum_engines: number;
  workers: number;
  session_count: number;
  requests: number;
  uptime_ns: number;
  active_sessions: number;
  total_sessions: number;
  queue_depth: number;
  queue_capacity: number;
  active_requests: number;
  completed_requests: number;
  failed_requests: number;
  cancelled_requests: number;
  openai_enabled: boolean;
  openai_ready: boolean;
  openai_port: number;
  rss_bytes: number;
  peak_rss_bytes: number;
  mapped_artifact_bytes: number;
  resident_host_bytes: number;
  resident_device_bytes: number;
  resources: ResourceObservation;
  [field: string]: unknown;
}
export interface HostObservation {
  state: HostState;
  status: HostSnapshot | null;
  host_instance: string | null;
  reason?: string | null;
  last_known?: LastKnownHost | null;
  [field: string]: unknown;
}
export interface Event {
  sequence: number;
  process: number;
  wall_time_ns: number;
  monotonic_time_ns: number;
  kind: string;
  severity: number;
  session: string;
  request: string;
  turn: string;
  phase: string;
  identity: string;
  measurement_available: number;
  measurement_completed: number;
  measurement_total: number;
  measurement_duration_ns: number;
  seconds: number;
  rate: number;
  [field: string]: unknown;
}
export interface Events {
  events: Array<Event>;
  next_sequence: number;
  truncated: boolean;
  host_instance: string;
  [field: string]: unknown;
}
export interface EngineMutationInput {
  model: string;
  generation: number;
  host_instance: string;
}
export interface SessionMutationInput {
  model: string;
  generation: number;
  name: string;
  host_instance: string;
  session_identity: string;
}
export interface SessionCreateInput {
  model: string;
  generation: number;
  name: string;
  host_instance: string;
}
export interface ModelListInput {
  query?: string;
  limit?: number;
}
export interface SearchInput {
  query?: string;
  author?: string;
  filter?: string;
  page?: number;
  limit?: number;
}
export interface InspectInput {
  repository: string;
  revision?: string;
}
export interface PackageInput {
  model: string;
  package: string;
}
export interface SourceInput {
  source: string;
}
export interface AcquisitionInput {
  repository: string;
  revision: string;
  representation: string;
  name?: string;
  authentication?: RegistryAuthentication;
  credential_ref?: string;
}
export type RegistryAuthentication = "anonymous" | "configured";
export interface AcquisitionCancelInput {
  source: string;
  expected_operation_id: string;
  expected_generation: number;
}
export interface BuildInput {
  model: string;
  quant?: string;
  dry_run?: boolean;
  expected_plan?: string;
}
export interface StorageInput {
  model: string;
  include_caches?: boolean;
}
export interface RemoteRepresentation {
  identity: string;
  format: string;
  precision: string;
  precision_evidence: string;
  file_pattern: string;
  compatibility: string;
  file_count: number;
  size_bytes: number;
  size_known: boolean;
  provisional: boolean;
  local: unknown;
  [field: string]: unknown;
}
export interface RemoteFile {
  path: string;
  kind: string;
  representation: string;
  size_bytes: number;
  size_known: boolean;
  [field: string]: unknown;
}
export interface RemoteModel {
  provider: string;
  repository: string;
  requested_revision: string;
  resolved_revision: string;
  kind: string;
  kind_evidence: string;
  model_identity: string;
  family_affinity: string;
  family_evidence: string;
  architecture: string;
  base_model: string;
  support_stage: string;
  product_status: string;
  engine_state: string;
  local_source_revision: boolean;
  local_package_revision: boolean;
  local_source: boolean;
  local_package: boolean;
  local_related_revision: boolean;
  kind_provisional: boolean;
  canonical: boolean;
  ranking_score: number;
  provider_rank: number;
  gated_known: boolean;
  gated: boolean;
  parameter_count_known: boolean;
  parameter_count: number;
  representations: Array<RemoteRepresentation>;
  files: Array<RemoteFile>;
  [field: string]: unknown;
}
export interface SearchResult {
  schema: string;
  authorities: Array<string>;
  query: string;
  provider_result_count: number;
  models: Array<RemoteModel>;
  [field: string]: unknown;
}
export interface PackageDetail {
  model: string;
  package: Artifact;
  profiles: Array<RuntimeProfile>;
  [field: string]: unknown;
}
export interface Acquisition {
  schema: string;
  operation_id: string;
  generation: number;
  provider: string;
  repository: string;
  target_id: string;
  family: string;
  revision: string;
  selection_identity: string;
  lifecycle: string;
  health: string;
  current_object: string | null;
  active: boolean;
  stop_available: boolean;
  resume_available: boolean;
  reason: string;
  result: string | null;
  expected_bytes: number | null;
  committed_bytes: number | null;
  selected_files: number | null;
  completed_files: number | null;
  current_rate_bytes_per_second: number | null;
  rolling_rate_bytes_per_second: number | null;
  [field: string]: unknown;
}
export interface AcquisitionObservation {
  acquisition: Acquisition;
  [field: string]: unknown;
}
export interface RegistryAccounts {
  providers: Array<RegistryAccount>;
  credential_configuration: string;
  [field: string]: unknown;
}
export interface StorageObservation {
  schema: string;
  rows: Array<unknown>;
  logical_bytes: number;
  [field: string]: unknown;
}
export interface RegistryAccount {
  provider: string;
  auth_state: string;
  account: string;
  credential_source: string;
  cli_present: boolean;
  status: string;
  blocker: string;
  credential_ref: string | null;
  credential_provisioning: string;
  [field: string]: unknown;
}
export interface LoadedModelEngine {
  profile_identity: string;
  variant: string;
  generation: number;
  sessions: number;
  [field: string]: unknown;
}
export interface AcquisitionResumeInput {
  source: string;
  expected_operation_id: string;
  expected_generation: number;
  authentication?: RegistryAuthentication;
  credential_ref?: string;
}
export type OutputChannel = "final_text" | "public_reasoning" | "tool_call" | "tool_result" | "control" | "error";
export interface GenerationChannel {
  channel: OutputChannel;
  text: string;
  bytes?: Array<number>;
  [field: string]: unknown;
}
export interface GenerationMetrics {
  prompt_tokens: number;
  generated_tokens: number;
  reasoning_tokens: number;
  final_tokens: number;
  stop_reason: number;
  total_completion_seconds: number;
  final_position: number;
  [field: string]: unknown;
}
export interface GenerationResult {
  host_instance: string;
  model: string;
  generation: number;
  session: string;
  channels: Array<GenerationChannel>;
  turn_identity: string | null;
  complete: boolean;
  progress?: Event;
  metrics?: GenerationMetrics;
  [field: string]: unknown;
}
export interface Acknowledgement {
  host_instance: string;
  acknowledged: boolean;
  reason: string;
  [field: string]: unknown;
}
export interface EngineResult {
  host_instance: string;
  engine: Engine;
  [field: string]: unknown;
}
export interface SessionResult {
  host_instance: string;
  session: Session;
  [field: string]: unknown;
}
export interface BuildResult {
  schema: string;
  model: string;
  state: string;
  changed: boolean;
  source?: string;
  revision?: string;
  target?: string;
  quant?: string;
  backend?: string;
  artifact?: string;
  profile?: string;
  action?: string;
  creation_reproducible?: boolean;
  runtime_binding?: string;
  binding_published?: boolean;
  plan_id?: string;
  planning?: BuildPlanning;
  [field: string]: unknown;
}
export interface JobSummary {
  job_id: string;
  operation: string;
  state: JobState;
  submitted_at_unix_ms: number;
  updated_at_unix_ms: number;
  reason: string | null;
  [field: string]: unknown;
}
export type RepresentationKind = "source" | "package";
export interface EvictInput {
  model: string;
  representation: string;
  kind: RepresentationKind;
  dry_run?: boolean;
  confirm?: boolean;
}
export interface SourceVerification {
  source: string;
  revision: string;
  payload_identity: string;
  payload_trust: string;
  shards: number;
  tensors: number;
  logical_tensor_bytes: number;
  physical_bytes_read: number;
  published_identity_reused: boolean;
  [field: string]: unknown;
}
export interface PackageVerification {
  model: string;
  package: string;
  checked: boolean;
  passed: boolean;
  native_status: number;
  sha256: string;
  digest_status: string;
  format: string;
  tensor_count: number;
  file_size: number;
  error_count: number;
  warning_count: number;
  [field: string]: unknown;
}
export interface Eviction {
  schema: string;
  changed: boolean;
  local: boolean;
  logical_bytes: number;
  allocated_bytes: number;
  path: string;
  [field: string]: unknown;
}
export interface ProfileScan {
  candidates: Array<ProfileCandidate>;
  truncated: boolean;
  [field: string]: unknown;
}
export interface ProfileCandidate {
  alias: string;
  family: string;
  model: string;
  scope: string;
  artifact_class: string;
  qprofile: string;
  calibration: string;
  path: string;
  [field: string]: unknown;
}
export interface ProfileInput {
  profile: string;
}
export interface ProfileVerification {
  profile: string;
  passed: boolean;
  identity_status: string;
  metadata_status: string;
  readiness_status: string;
  status: string;
  reason: string;
  registered_sha256: string;
  current_sha256: string;
  registered_size: number;
  current_size: number;
  [field: string]: unknown;
}
export interface ProfileCreateInput {
  model: string;
  package: string;
  alias: string;
  base_profile?: string;
  context?: number;
}
export interface ProfileCreated {
  profile: string;
  package: string;
  file_size: number;
  created: boolean;
  [field: string]: unknown;
}
export interface ProfileRemoveInput {
  profile: string;
  expected_package: string;
  confirm: boolean;
}
export interface ProfileRemoved {
  profile: string;
  removed: boolean;
  [field: string]: unknown;
}
export interface SourceCleanupInput {
  source: string;
  expected_operation_id: string;
  expected_generation: number;
  stale_locks?: boolean;
  failed_partials?: boolean;
  receipts?: boolean;
  logs?: boolean;
  provider_cache?: boolean;
  dry_run?: boolean;
  confirm?: boolean;
}
export interface SourceCleanup {
  schema: string;
  target: string;
  status: string;
  dry_run: boolean;
  yes: boolean;
  delete_candidates: Array<string>;
  deleted_paths: number;
  missing: number;
  [field: string]: unknown;
}
export type ProfileReadiness = "ready" | "blocked" | "incompatible" | "unavailable" | "unknown";
export interface LastKnownHost {
  host_instance: string;
  status: HostSnapshot;
  observed_at_unix_ms: number;
  [field: string]: unknown;
}
export interface BuildPlanning {
  schema: string;
  readiness: ProfileReadiness;
  basis: BuildPlanningBasis;
  reason: string | null;
  native_status: number | null;
  owner: string | null;
  execution_strategy: string | null;
  runtime_admission: BuildEvidencePosture;
  quality_evidence: BuildEvidencePosture;
  performance_evidence: BuildEvidencePosture;
  [field: string]: unknown;
}
export type BuildPlanningBasis = "admitted_recipe" | "verified_profile" | "not_admitted";
export type BuildEvidencePosture = "not_evaluated";
export type HostOwnership = "managed" | "external" | "unconfigured";
export interface HostControl {
  schema: string;
  ownership: HostOwnership;
  revision: number;
  state: HostState;
  host_instance: string | null;
  configured: boolean;
  service_control_granted: boolean;
  can_start: boolean;
  can_stop: boolean;
  can_restart: boolean;
  reason: string | null;
  inference_port: number | null;
  [field: string]: unknown;
}
export interface HostStartInput {
  expected_revision: number;
}
export interface HostStopInput {
  expected_revision: number;
  host_instance: string;
  acknowledge_disruption: boolean;
}
export type HostControlPhase = "stopping" | "stopped" | "starting" | "running";
export interface HostControlResult {
  schema: string;
  phase: HostControlPhase;
  revision: number;
  previous_host_instance: string | null;
  host_instance: string | null;
  models_restored: boolean;
  [field: string]: unknown;
}
export interface JobResults {
  "engine.load": EngineResult;
  "engine.unload": EngineResult | Acknowledgement;
  "session.create": SessionResult;
  "session.fork": SessionResult;
  "session.close": Acknowledgement;
  "session.reset": Acknowledgement;
  "generation.start": GenerationResult;
  "generation.cancel": Acknowledgement;
  "acquisition.start": AcquisitionObservation;
  "acquisition.resume": AcquisitionObservation;
  "acquisition.cancel": AcquisitionObservation;
  "build.start": BuildResult;
  "source.verify": SourceVerification;
  "package.verify": PackageVerification;
  "model.evict": Eviction;
  "profile.verify": ProfileVerification;
  "profile.create": ProfileCreated;
  "profile.remove": ProfileRemoved;
  "source.cleanup": SourceCleanup;
  "profile.scan": ProfileScan;
  "host.start": HostControlResult;
  "host.stop": HostControlResult;
  "host.restart": HostControlResult;
}
export type Job = { [O in keyof JobResults]: Omit<JobRecord, "operation" | "result" | "input"> & { operation: O; input: OperationInputs[O]; result: JobResults[O] | null } }[keyof JobResults];
export interface OperationInputs {
  "management.capabilities": EmptyInput;
  "model.list": ModelListInput;
  "model.get": ModelInput;
  "engine.list": EmptyInput;
  "engine.load": EngineLoadInput;
  "engine.unload": EngineMutationInput;
  "host.get": EmptyInput;
  "session.list": EngineInput;
  "session.get": SessionInput;
  "session.create": SessionCreateInput;
  "session.fork": SessionForkInput;
  "session.close": SessionMutationInput;
  "generation.start": GenerationInput;
  "generation.cancel": GenerationCancelInput;
  "job.list": ListInput;
  "job.get": JobInput;
  "observe.events": EventsInput;
  "model.search": SearchInput;
  "model.inspect": InspectInput;
  "model.storage": StorageInput;
  "registry.accounts": EmptyInput;
  "package.get": PackageInput;
  "acquisition.get": SourceInput;
  "acquisition.start": AcquisitionInput;
  "acquisition.resume": AcquisitionResumeInput;
  "acquisition.cancel": AcquisitionCancelInput;
  "build.start": BuildInput;
  "session.reset": SessionMutationInput;
  "source.verify": SourceInput;
  "package.verify": PackageInput;
  "model.evict": EvictInput;
  "profile.scan": EmptyInput;
  "profile.verify": ProfileInput;
  "profile.create": ProfileCreateInput;
  "profile.remove": ProfileRemoveInput;
  "source.cleanup": SourceCleanupInput;
  "host.control": EmptyInput;
  "host.start": HostStartInput;
  "host.stop": HostStopInput;
  "host.restart": HostStopInput;
}
export interface OperationOutputs {
  "management.capabilities": Capabilities;
  "model.list": ModelList;
  "model.get": ModelDetail;
  "engine.list": EngineList;
  "engine.load": Job;
  "engine.unload": Job;
  "host.get": HostObservation;
  "session.list": SessionList;
  "session.get": SessionDetail;
  "session.create": Job;
  "session.fork": Job;
  "session.close": Job;
  "generation.start": Job;
  "generation.cancel": Job;
  "job.list": JobList;
  "job.get": Job;
  "observe.events": Events;
  "model.search": SearchResult;
  "model.inspect": SearchResult;
  "model.storage": StorageObservation;
  "registry.accounts": RegistryAccounts;
  "package.get": PackageDetail;
  "acquisition.get": AcquisitionObservation;
  "acquisition.start": Job;
  "acquisition.resume": Job;
  "acquisition.cancel": Job;
  "build.start": Job;
  "session.reset": Job;
  "source.verify": Job;
  "package.verify": Job;
  "model.evict": Job;
  "profile.scan": Job;
  "profile.verify": Job;
  "profile.create": Job;
  "profile.remove": Job;
  "source.cleanup": Job;
  "host.control": HostControl;
  "host.start": Job;
  "host.stop": Job;
  "host.restart": Job;
}
export type ManagementOperation = keyof OperationInputs;
export interface ManagementInvocation<O extends ManagementOperation = ManagementOperation> {
  schema: "yvex.management.request.v2";
  request_id: string;
  operation: O;
  input: OperationInputs[O];
}
export interface ManagementObservation<T> { request_id: string; device_identity: string; authenticated_peer: string; value: T; }
export interface ManagementFailure { code: string; dispatch_state: DispatchState; reason?: string; request_id?: string; }
/** Client observation freshness; never infer an empty result from absent value. */
export type ReadPosture = "never_observed" | "loading" | "current" | "stale" | "unavailable" | "failed" | "unsupported";
export interface ReadObservation<T> { posture: ReadPosture; observedAt?: number; value?: T; failure?: ManagementFailure; }
export interface IdentityObservation {
  schema: string;
  device_identity: string;
  display_name: string;
  protocol: string;
  pairing_available: boolean;
}
export interface HostCandidate {
  endpoint: string;
  identity: IdentityObservation;
  certificate_sha256: string;
}
export type PairingPosture = "pending" | "approved" | "revoked" | "expired" | "refused";
export interface PairingObservation {
  schema: string;
  request_id: string;
  posture: PairingPosture;
  scope: string;
  expires_at_unix_ms: number;
  reason: string | null;
}
export type ConnectionTransport = "https" | "local";
export type ConnectionPosture = "unpaired" | "pending" | "approved" | "revoked" | "expired" | "refused";
export interface ConnectionProfile {
  profile_ref: string;
  transport: ConnectionTransport;
  endpoint: string;
  device_identity: string;
  peer_identity: string;
  display_name: string;
  client_name: string;
  pairing_posture: ConnectionPosture;
  expires_at_unix_ms: number | null;
}
export interface DiscoveredHost {
  service_name: string;
  endpoint: string;
  display_name: string;
  advertised_device_identity: string | null;
  trusted: boolean;
}
export type OwnerPosture = "approved" | "revoked";
export type OwnerProfilePosture = "prepared" | "claiming" | "approved" | "revoked";
export type OwnerActionKind = "pairing_open" | "pairing_approve" | "pairing_revoke" | "owner_revoke" | "service_control_grant" | "service_control_revoke";
export type OwnerActionPosture = "applied" | "refused";
export interface OwnerInvitationPreview {
  endpoint: string;
  device_identity: string;
  invitation_id: string;
  expires_at_unix_ms: number;
}
export interface OwnerProfile {
  profile_ref: string;
  endpoint: string;
  device_identity: string;
  peer_identity: string;
  client_name: string;
  posture: OwnerProfilePosture;
  pending_requests: Array<string>;
}
export interface OwnerObservation {
  schema: string;
  scope: string;
  owner_ref: string;
  client_name: string;
  posture: OwnerPosture;
  revision: number;
}
export interface OwnerPeer {
  request_id: string;
  client_name: string;
  posture: PairingPosture;
  scope: string;
  expires_at_unix_ms: number;
  service_control_granted?: boolean;
}
export interface OwnerAdministrationObservation {
  schema: string;
  scope: string;
  owner_ref: string;
  revision: number;
  open_until_unix_ms: number;
  peers: Array<OwnerPeer>;
  available_actions?: Array<OwnerActionKind>;
}
export interface OwnerActionRequest {
  schema: string;
  request_id: string;
  expected_revision: number;
  action: OwnerActionKind;
  target_ref: string | null;
}
export interface OwnerActionReceipt {
  schema: string;
  scope: string;
  owner_ref: string;
  request_id: string;
  action: OwnerActionKind;
  target_ref: string | null;
  revision: number;
  posture: OwnerActionPosture;
  reason: string | null;
}
