/* Shared host/device result-slot layout for CUDA sampling and speculation. */
#ifndef SRC_BACKEND_CUDA_SAMPLING_LAYOUT_H_INCLUDED
#define SRC_BACKEND_CUDA_SAMPLING_LAYOUT_H_INCLUDED
enum {
    YVEX_CUDA_SAMPLING_TOP_K_COUNT = 0,
    YVEX_CUDA_SAMPLING_MIN_P_COUNT,
    YVEX_CUDA_SAMPLING_TYPICAL_COUNT,
    YVEX_CUDA_SAMPLING_TOP_P_COUNT,
    YVEX_CUDA_SAMPLING_COUNT_FIELDS
};
enum {
    YVEX_CUDA_SAMPLING_SELECTED_PROBABILITY = 0,
    YVEX_CUDA_SAMPLING_MIN_P_THRESHOLD,
    YVEX_CUDA_SAMPLING_ENTROPY,
    YVEX_CUDA_SAMPLING_TYPICAL_MASS,
    YVEX_CUDA_SAMPLING_TOP_P_MASS,
    YVEX_CUDA_SAMPLING_NORMALIZATION_ERROR,
    YVEX_CUDA_SAMPLING_STATISTIC_FIELDS
};
enum {
    YVEX_CUDA_SAMPLING_SELECTED_LOGIT = 0,
    YVEX_CUDA_SAMPLING_MAXIMUM_LOGIT,
    YVEX_CUDA_SAMPLING_VALUE_FIELDS
};
enum {
    YVEX_CUDA_SAMPLING_SELECTED_TOKEN = 0,
    YVEX_CUDA_SAMPLING_NUMERIC_FALLBACK,
    YVEX_CUDA_SAMPLING_SELECTION_FIELDS
};
enum {
    YVEX_CUDA_SPECULATION_PROPOSED_COUNT = 0,
    YVEX_CUDA_SPECULATION_ACCEPTED_COUNT,
    YVEX_CUDA_SPECULATION_REJECTED_COUNT,
    YVEX_CUDA_SPECULATION_COMMITTED_COUNT,
    YVEX_CUDA_SPECULATION_REJECTION_INDEX,
    YVEX_CUDA_SPECULATION_ALL_ACCEPTED,
    YVEX_CUDA_SPECULATION_CORRECTION_PRESENT,
    YVEX_CUDA_SPECULATION_BONUS_PRESENT,
    YVEX_CUDA_SPECULATION_CORRECTION_TOKEN,
    YVEX_CUDA_SPECULATION_RESULT_FIELDS
};
#endif
