#!/usr/bin/env python3
"""Generate the canonical YVEX Rust/TypeScript client contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / 'rust/contract/management.json'


def render(contract):
    types = contract['types']
    inputs = {row['input'] for row in contract['operations']}
    def typ(value, language):
        if ':' in value:
            prefix, nested = value.split(':', 1)
            inner = typ(nested, language)
            if prefix == 'array': return f'Vec<{inner}>' if language == 'rs' else f'Array<{inner}>'
            if prefix == 'map': return f'std::collections::BTreeMap<String, {inner}>' if language == 'rs' else f'Record<string, {inner}>'
            if prefix in ('optional', 'nullable'): return f'Option<{inner}>' if language == 'rs' else (inner if prefix == 'optional' else f'{inner} | null')
            raise ValueError(prefix)
        primitives = {'string':('String','string'),'bool':('bool','boolean'),'json':('serde_json::Value','unknown'),
                      'i64':('i64','number'),'u64':('u64','number'),'u32':('u32','number'),'f64':('f64','number')}
        if value in primitives: return primitives[value][language == 'ts']
        if value not in types: raise ValueError(value)
        return value
    rs=['// Generated by sdk/tools/generate.py; edit contract/management.json.', 'use serde::{Deserialize, Serialize};']
    ts=['// Generated by sdk/tools/generate.py; public YVEX types, no renderer transport.']
    for name, fields in types.items():
        if '$enum' in fields:
            rs += ['#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]', '#[serde(rename_all = "snake_case")]',f'pub enum {name} {{']
            rs += ['    '+''.join(p.title() for p in value.split('_'))+',' for value in fields['$enum']]
            rs += ['}']
            ts += [f'export type {name} = '+ ' | '.join(json.dumps(v) for v in fields['$enum'])+';']
            continue
        # Do not derive Debug for data: input may contain a public-generation prompt.
        rs += ['#[derive(Clone, Serialize, Deserialize)]']
        if name in inputs: rs += ['#[serde(deny_unknown_fields)]']
        rs += [f'pub struct {name} {{']
        ts += [f'export interface {"JobRecord" if name == "Job" else name} {{']
        for field, value in fields.items():
            if value.startswith('optional:'): rs += ['    #[serde(default, skip_serializing_if = "Option::is_none")]']
            if value.startswith('nullable:'): rs += ['    #[serde(default)]']
            rs += [f'    pub {field}: {typ(value,"rs")},']
            ts += [f'  {field}{"?" if value.startswith("optional:") else ""}: {typ(value,"ts")};']
        if name not in inputs:
            rs += ['    #[serde(flatten)]', '    pub additional: std::collections::BTreeMap<String, serde_json::Value>,']
            if name != 'Job': ts += ['  [field: string]: unknown;']
        rs += ['}']; ts += ['}']
    rs += ['pub mod operations {', '    use super::*;', '    use crate::management::Operation;']
    for op in contract['operations']:
        name=''.join(p.title() for p in op['operation'].replace('.','_').split('_'))
        rs += [f'    pub struct {name};',f'    impl Operation for {name} {{',f'        type Input = super::{op["input"]};',f'        type Output = super::{op["output"]};',f'        const ID: &\'static str = "{op["operation"]}";',f'        const KIND: OperationKind = OperationKind::{op["kind"].title()};','    }']
    rs += ['}']
    rs += ['pub(crate) fn validate_input(operation: &str, value: &serde_json::Value) -> Result<(), serde_json::Error> {', '    match operation {']
    for op in contract['operations']:
        rs += [f'        "{op["operation"]}" => serde_json::from_value::<{op["input"]}>(value.clone()).map(|_| ()),']
    rs += ['        _ => Err(serde::de::Error::custom("unknown operation")),', '    }', '}']
    rs += ['pub(crate) fn validate_projection(operation: &str, value: &serde_json::Value) -> Result<(), serde_json::Error> {', '    match operation {']
    for op in contract['operations']:
        rs += [f'        "{op["operation"]}" => serde_json::from_value::<{op["output"]}>(value.clone()).map(|_| ()),' ]
    rs += ['        _ => unreachable!("validated operation"),', '    }', '}']
    rs += ['pub(crate) fn validate_job(job: &Job) -> Result<(), serde_json::Error> {', '    match job.operation.as_str() {']
    for op in contract['operations']:
        if op['kind']!='job': continue
        candidates=contract['job_results'][op['operation']]
        rs += [f'        "{op["operation"]}" => {{',f'            serde_json::from_value::<{op["input"]}>(job.input.clone())?;', '            if let Some(result) = &job.result {']
        parse=f'serde_json::from_value::<{candidates[0]}>(result.clone()).map(|_| ())'
        for alternative in candidates[1:]: parse+=f'.or_else(|_| serde_json::from_value::<{alternative}>(result.clone()).map(|_| ()))'
        rs += ['                '+parse+'?;', '            }', '            Ok(())', '        }']
    rs += ['        _ => Err(serde::de::Error::custom("unknown job operation")),', '    }', '}']
    rs += ['pub const OPERATIONS: &[(&str, OperationKind)] = &[']
    rs += [f'    ("{op["operation"]}", OperationKind::{op["kind"].title()}),' for op in contract['operations']]
    rs += ['];']
    families = {'model':'Models','acquisition':'Acquisitions','build':'Builds','package':'Packages','host':'Hosts','engine':'Engines','session':'Sessions','generation':'Generations','job':'Jobs','observe':'Observe','source':'Sources','profile':'Profiles','registry':'Registries','management':'Management'}
    for family, domain in families.items():
        selected=[op for op in contract['operations'] if op['operation'].split('.')[0]==family]
        if not selected: continue
        accessor=domain.lower()
        rs += [f"pub struct {domain}<'a>(&'a crate::management::Client);", 'impl crate::management::Client {', f"    pub fn {accessor}(&self) -> {domain}<'_> {{ {domain}(self) }}", '}']
        rs += [f"impl {domain}<'_> {{"]
        for op in selected:
            marker=''.join(p.title() for p in op['operation'].replace('.','_').split('_'))
            method=op['operation'].split('.')[1]
            if op['kind']=='read':
                rs += [f"    pub fn {method}(&self, input: &{op['input']}) -> Result<crate::management::Observation<{op['output']}>, crate::management::Error> {{",f"        self.0.read::<operations::{marker}>(input)", '    }']
            else:
                rs += [f"    pub fn prepare_{method}(&self, input: &{op['input']}) -> Result<crate::management::Prepared<operations::{marker}>, crate::management::Error> {{",f"        self.0.prepare::<operations::{marker}>(input)", '    }']
        rs += ['}']
    job_results={op:' | '.join(values) for op,values in contract['job_results'].items()}
    ts += ['export interface JobResults {']+[f'  "{op}": {result};' for op,result in job_results.items()]+['}']
    ts += ['export type Job = { [O in keyof JobResults]: Omit<JobRecord, "operation" | "result" | "input"> & { operation: O; input: OperationInputs[O]; result: JobResults[O] | null } }[keyof JobResults];']
    ts += ['export interface OperationInputs {']+[f'  "{op["operation"]}": {op["input"]};' for op in contract['operations']]+['}']
    ts += ['export interface OperationOutputs {']+[f'  "{op["operation"]}": {op["output"]};' for op in contract['operations']]+['}']
    ts += ['export type ManagementOperation = keyof OperationInputs;', 'export interface ManagementInvocation<O extends ManagementOperation = ManagementOperation> {',
           f'  schema: "{contract["request_schema"]}";', '  request_id: string;','  operation: O;','  input: OperationInputs[O];','}',
           'export interface ManagementObservation<T> { request_id: string; device_identity: string; authenticated_peer: string; value: T; }',
           'export interface ManagementFailure { code: string; dispatch_state: DispatchState; reason?: string; request_id?: string; }']
    ts += ['/** Client observation freshness; never infer an empty result from absent value. */',
           'export type ReadPosture = "never_observed" | "loading" | "current" | "stale" | "unavailable" | "failed" | "unsupported";',
           'export interface ReadObservation<T> { posture: ReadPosture; observedAt?: number; value?: T; failure?: ManagementFailure; }']
    return '\n'.join(rs)+'\n','\n'.join(ts)+'\n'


def render_network():
    types=json.loads((ROOT/'rust/contract/network.json').read_text())['types']
    rs=['// Generated by sdk/tools/generate.py; safe native connection records.', 'use serde::{Serialize, Deserialize};']
    ts=[]
    def kind(value):
        if value.startswith('optional:'):
            r,t=kind(value.removeprefix('optional:'));return f'Option<{r}>',t
        if value.startswith('nullable:'):
            r,t=kind(value.removeprefix('nullable:'));return f'Option<{r}>',f'{t} | null'
        if value.startswith('array:'):
            r,t=kind(value.removeprefix('array:'));return f'Vec<{r}>',f'Array<{t}>'
        return {'string':'String','bool':'bool','u64':'u64'}.get(value,value), {'string':'string','bool':'boolean','u64':'number'}.get(value,value)
    for name,fields in types.items():
        rs += ['#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]']
        if '$enum' in fields:
            rs += ['#[serde(rename_all="snake_case")]',f'pub enum {name} {{'+','.join(v.title().replace('_','') for v in fields['$enum'])+'}']
            ts += [f'export type {name} = '+' | '.join(json.dumps(v) for v in fields['$enum'])+';']
        else:
            rs += ['#[serde(deny_unknown_fields)]',f'pub struct {name} {{']
            ts += [f'export interface {name} {{']
            for field,value in fields.items():
                r,t=kind(value)
                if value.startswith('optional:'): rs += ['    #[serde(default, skip_serializing_if = "Option::is_none")]']
                rs += [f'    pub {field}: {r},']
                ts += [f'  {field}{"?" if value.startswith("optional:") else ""}: {t};']
            rs+=['}'];ts+=['}']
    return '\n'.join(rs)+'\n','\n'.join(ts)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    contract=json.loads(CONTRACT.read_text());seen=set()
    for op in contract['operations']:
        if op['operation'] in seen: raise SystemExit('duplicate management operation')
        seen.add(op['operation'])
    rust,ts=render(contract)
    network_rs,network_ts=render_network()
    outputs=[('rust/src/management/types.rs',rust),('typescript/index.ts',ts+network_ts),('rust/src/management/network_types.rs',network_rs)]
    for relative, content in outputs:
        path=ROOT/relative
        if args.check:
            if not path.is_file() or path.read_text()!=content: raise SystemExit(f'stale YVEX projection: {relative}')
        else: path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content)
    print(f'YVEX management projection: PASS {len(seen)} operations')


if __name__=='__main__': main()
